 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.h
 *
 * Description: Post-build configuration file for TM4C123GH6PM Microcontroller - Port Driver.
 *
 * Author: Ziad Hisham
 ******************************************************************************/
#include "Port.h"

/*
Module Version 1.0.0
*/
#define PORT_PBCFG_SW_MAJOR_VERSION           (1U)
#define PORT_PBCFG_SW_MINOR_VERSION           (0U)
#define PORT_PBCFG_SW_PATCH_VERSION           (0U)

/*
AUTOSAR Version 4.0.3
*/
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION   (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION   (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION   (3U)

/* AUTOSAR version checking if Port_PBcfg.c and port.h align */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of Port_PBcfg.c does not match the expected version"
#endif

/* Software version checking if Port_PBcfg.c and port.h align */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif
   
   const Port_ConfigType  Port_ConfigPin_ex= {
     /*PORTS A -> D have 8 pins*/
     PORT_A, PORT_PIN0, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_A, PORT_PIN1, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_A, PORT_PIN2, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_A, PORT_PIN3, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_A, PORT_PIN4, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_A, PORT_PIN5, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_A, PORT_PIN6, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_A, PORT_PIN7, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     
     PORT_B, PORT_PIN0, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_B, PORT_PIN1, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_B, PORT_PIN2, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_B, PORT_PIN3, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_B, PORT_PIN4, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_B, PORT_PIN5, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_B, PORT_PIN6, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_B, PORT_PIN7, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     
     PORT_C, PORT_PIN0, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_C, PORT_PIN1, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_C, PORT_PIN2, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_C, PORT_PIN3, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_C, PORT_PIN4, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_C, PORT_PIN5, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_C, PORT_PIN6, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_C, PORT_PIN7, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     
     PORT_D, PORT_PIN0, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_D, PORT_PIN1, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_D, PORT_PIN2, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_D, PORT_PIN3, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_D, PORT_PIN4, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_D, PORT_PIN5, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_D, PORT_PIN6, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_D, PORT_PIN7, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     
     /*PORT E 6 pins 0 -> 5*/
     PORT_E, PORT_PIN0, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_E, PORT_PIN1, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_E, PORT_PIN2, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_E, PORT_PIN3, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_E, PORT_PIN4, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_E, PORT_PIN5, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,

     /*PORT F 5 pins 0 -> 4  Push buttons and leds*/
     PORT_F, PORT_PIN0, PORT_PIN_IN, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_F, PORT_PIN1, PORT_PIN_OUT, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_F, PORT_PIN2, PORT_PIN_OUT, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_F, PORT_PIN3, PORT_PIN_OUT, OFF, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,
     PORT_F, PORT_PIN4, PORT_PIN_IN, PULL_UP, STD_LOW, PORTPIN_MODE_DIO, STD_ON, STD_ON,

   };